

services:
  frontend:
    build: ./frontend/snippetclip
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=mariadb
      - DATABASE_USER=root
      - DATABASE_PASSWORD=example
      - DATABASE_NAME=voting_app
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ./mariadb_data:/var/lib/mysql


  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  mariadb_data: